FROM node:16-buster-slim
ENV PORT 3200

WORKDIR /app
COPY ./package.json /app/
COPY ./supergraph.graphql /app/
COPY ./server-unmanaged.js /app/server.js

RUN npm install

EXPOSE ${PORT}
CMD [ "npm", "start" ]